# Generated by Django 6.0.6 on 2026-07-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_cartitem_invoice'),
        ('products', '0006_add_service_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.business'),
        ),
    ]
