# Generated by Django 6.0.6 on 2026-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_business_about_us_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='events_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='faqs_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='gallery_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='packages_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='services_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='business',
            name='team_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='testimonials_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('product', 'Product Business'), ('service', 'Service Business'), ('trust', 'Trust / NGO'), ('logistics', 'Logistics / Transport')], default='product', max_length=50),
        ),
    ]
