# Generated by Django 6.0.6 on 2026-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('manager', 'Store Manager'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
