# Generated by Django 6.0.6 on 2026-07-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0006_add_service_json_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='donations/screenshots/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='products.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('bank_transfer_enabled', models.BooleanField(default=False)),
                ('upi_id', models.CharField(blank=True, help_text='For manual UPI payments/Donations', max_length=100)),
                ('bank_details', models.TextField(blank=True, help_text='For manual Bank Transfers')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='products.business')),
            ],
        ),
    ]
